baseurl = "https://henriquedias.com/"
disqusShortname = "hacdias"
languageCode = "en_GB"
paginate = "18"
paginatePath = "page"
pluralizelisttitles = false
removePathAccents = true
title = "Henrique Dias"

[author]
  Email = "hacdias@gmail.com"
  Image = "henrique.png"
  JobTitle = "Author"
  Name = "Henrique Dias"
  Telephone = "351 965 856 140"

[params]
  Analytics = "59697241-1"
  Description = "I'm Henrique Dias, portuguese and I live in Portugal. I am attending secondary school in a course called “Science and Technology” that I hope finish in 2017."
  Image = "images/home.jpg"
  [params.Webmaster]
    Bing = "B471CBBC9EF6900039C6BBF251EF277C"
    Google = "nVQ4_x6m6ZTRAzclMPNxpB0iMgK-xoIj_d-l85u32nY"

[social]
  Facebook = "hacdias"
  GitHub = "hacdias"
  GooglePlus = "HenriqueDias"
  Instagram = "hacdias"
  LinkedIn = "hacdias"
  Twitter = "hacdias"
  YouTube = "UCEJe-YgDEvr351w1oNjzolw"
