baseurl: 'https://henriquedias.com/'
disqusShortname: hacdias
languageCode: en
paginate: 15
pluralizelisttitles: false
removePathAccents: true
title: Henrique Dias

params:
  Analytics: 59697241-1
  Description: >
    Student. 17. Passionate about programming. Music and photography addicted. I
    love the idea of improving the world using technology.
  image: home/1
  Author:
    Email: hacdias@gmail.com
    image: henrique.jpg
    JobTitle: Developer
    Name: Henrique Dias
    Telephone: 351 965 856 140
  Social:
    Facebook: hacdias
    GitHub: hacdias
    GooglePlus: HenriqueDias
    Instagram: hacdias
    LinkedIn: hacdias
    Twitter: hacdias
    YouTube: UCEJe-YgDEvr351w1oNjzolw
  Webmaster:
    Bing: B471CBBC9EF6900039C6BBF251EF277C
    Google: nVQ4_x6m6ZTRAzclMPNxpB0iMgK-xoIj_d-l85u32nY

menu:
  main:
    - name: About
      weight: 1
      identifier: about
      url: /about/
    - name: Blog
      weight: 2
      url: /blog/