baseurl: 'https://hacdias.com/'
disqusShortname: hacdias
languageCode: en
paginate: 10
pluralizelisttitles: false
removePathAccents: true
title: Henrique Dias (@hacdias)
pygmentsStyle: github
summarylength: 30

params:
  Analytics: 59697241-1
  Description: >-
    I study Information Systems and Computer Engineering at Instituto Superior TÃ©cnico.
    Digging into the decentralized web with IPFS.
  image: images/lamps.jpg
  Author:
    Email: hacdias@gmail.com
    image: henrique.jpg
    JobTitle: Developer
    Name: Henrique Dias
  Social:
    Facebook: hacdias
    GitHub: hacdias
    Instagram: hacdias
    LinkedIn: hacdias
    Twitter: hacdias
  Webmaster:
    Bing: B471CBBC9EF6900039C6BBF251EF277C
    Google: nVQ4_x6m6ZTRAzclMPNxpB0iMgK-xoIj_d-l85u32nY

menu:
  main:
    - name: About
      weight: 1
      identifier: about
      pre: ğŸ§‘
      url: /about/
    - name: Writing
      weight: 2
      pre: ğŸ“°
      url: /blog/
    - name: Projects
      weigth: 3
      pre: ğŸ“¦
      url: /projects/
    - name: PGP Key
      weight: 4
      pre: ğŸ”‘
      url: https://keybase.io/hacdias/pgp_keys.asc?fingerprint=4dc16358711be325fb3633cf2e80d38374cd55aa
  social:
    - name: Email
      weight: 1
      pre: ğŸ“§
      url: mailto:hacdias@gmail.com
    - name: GitHub
      weight: 2
      pre: ğŸ‘¨â€ğŸ’»
      url: https://github.com/hacdias
    - name: Twitter
      weigth: 3
      pre: ğŸ•Šï¸
      url: https://twitter.com/hacdias
    - name: Instagram
      weight: 4
      pre: ğŸ“·
      url: https://instagram.com/hacdias
